# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  branches:
    include:
      - PIC123/feat-docker
      - refs/tags/{docker*}
pr: none # disable CI build for PR

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

  
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'fb116db9-622e-4b02-b5ba-65cc76f2cb4f'
    command: 'login'

- bash: | 
    set -e
    
    export DISPLAY=:99.0
    echo "Starting Build"

    npm ci  # do a clean install
    npm run build

  displayName: 'Run npm build'

- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'PELITTLE TEAM - CSE DWR (d36d0808-a967-4f73-9fdc-32ea232fc81d)'
    scriptPath: './scripts/connect-acr.sh'
